apiVersion: v1
kind: Service
metadata:
  name: test-cp-kafka-rest
  labels:
    app: cp-kafka-rest
    chart: cp-kafka-rest-0.1.0
    release: test
    heritage: Tiller
spec:
  ports:
    - name: rest-proxy
      port: 8082
  selector:
    app: cp-kafka-rest
    release: test
  type: LoadBalancer
